(function(){
    const promptEl = document.getElementById("promptInput");
    const generateBtn = document.getElementById("generate");
    const previewBtn = document.getElementById("previewBtn");
    const downloadBtn = document.getElementById("download");
    const codeEl = document.getElementById("code");
    const copyContainer = document.querySelector(".copy-buttons");

    // Rules for offline prompt recognition
    const rules = {
        pages: ['home','about','contact','index','blog','shop','dashboard'],
        features: ['calculator','login','signup','form','database','search','cart','payment'],
        languages: ['python','java','c','c++','ruby','php','webpage']
    };

    // Core syntax model for each language
    const languageSyntax = {
        python: {
            start: 'def main():\n',
            print: 'print',
            comment: '#',
            example: `def greet(name):\n    print(f"Hello {name}")\n\ngreet("World")`
        },
        java: {
            start: 'public class Main {\n    public static void main(String[] args){\n',
            print: 'System.out.println',
            comment: '//',
            example: `public class Main {\n    public static void main(String[] args){\n        System.out.println("Hello World");\n    }\n}`
        },
        c: {
            start: '#include <stdio.h>\nint main(){\n',
            print: 'printf',
            comment: '//',
            example: `#include <stdio.h>\nint main(){\n    printf("Hello World\\n");\n    return 0;\n}`
        },
        'c++': {
            start: '#include <iostream>\nusing namespace std;\nint main(){\n',
            print: 'cout',
            comment: '//',
            example: `#include <iostream>\nusing namespace std;\nint main(){\n    cout << "Hello World" << endl;\n    return 0;\n}`
        },
        ruby: {
            start: '',
            print: 'puts',
            comment: '#',
            example: `def greet(name)\n  puts "Hello #{name}"\nend\n\ngreet("World")`
        },
        php: {
            start: '<?php\n',
            print: 'echo',
            comment: '//',
            example: `<?php\necho "Hello World";\n?>`
        },
        webpage: {
            start: '<!DOCTYPE html>\n<html>\n<head><title>',
            comment: '<!--',
            example: `<!DOCTYPE html>\n<html>\n<head>\n<title>My Page</title>\n</head>\n<body>\n<h1>Hello World</h1>\n</body>\n</html>`
        }
    };

    // Analyze prompt sentence by sentence, word by word
    function analyzePrompt(prompt){
        const sentences = prompt.match(/[^.!?]+[.!?]*/g) || [prompt];
        const plan = {files:[], lang:'webpage'}; // default language

        sentences.forEach(sentence=>{
            const words = sentence.toLowerCase().split(/\s+/);
            words.forEach(word=>{
                if(rules.pages.includes(word) && !plan.files.includes(word+'.html')) plan.files.push(word+'.html');
                if(rules.features.includes(word)){
                    switch(word){
                        case 'calculator': if(!plan.files.includes('calculator.py')) plan.files.push('calculator.py'); break;
                        case 'login': if(!plan.files.includes('login.html')) plan.files.push('login.html'); break;
                        case 'signup': if(!plan.files.includes('signup.html')) plan.files.push('signup.html'); break;
                        case 'form': if(!plan.files.includes('form.js')) plan.files.push('form.js'); break;
                        case 'database': if(!plan.files.includes('database.py')) plan.files.push('database.py'); break;
                        case 'search': if(!plan.files.includes('search.js')) plan.files.push('search.js'); break;
                        case 'cart': if(!plan.files.includes('cart.js')) plan.files.push('cart.js'); break;
                        case 'payment': if(!plan.files.includes('payment.js')) plan.files.push('payment.js'); break;
                    }
                }
                if(rules.languages.includes(word)) plan.lang = word;
            });
        });

        if(plan.files.length===0) plan.files.push('index.html');
        return plan;
    }

    // Improved real syntax-aware code generator
    function generateCode(file, prompt, lang='webpage') {
        const syntax = languageSyntax[lang] || languageSyntax.webpage;

        if (file.endsWith('.html')) {
            return `${syntax.start}${prompt}</title></head><body><h1>${prompt}</h1></body></html>`;
        }

        if (file.endsWith('.py')) {
            return `${syntax.comment} Generated by ProjectBuilder\n${syntax.start}    ${syntax.print}("${prompt} - running")\n\nif __name__=="__main__":\n    main()`;
        }

        if (file.endsWith('.java')) {
            return `${syntax.start}        ${syntax.print}("${prompt}");\n    }\n}`;
        }

        if (file.endsWith('.c')) {
            return `${syntax.start}    ${syntax.print}("${prompt}\\n");\n    return 0;\n}`;
        }

        if (file.endsWith('.cpp')) {
            return `${syntax.start}    ${syntax.print} << "${prompt}" << endl;\n    return 0;\n}`;
        }

        if (file.endsWith('.rb')) {
            return `${syntax.comment} ${prompt}\n${syntax.print} "${prompt}"`;
        }

        if (file.endsWith('.php')) {
            return `${syntax.start}${syntax.print} '${prompt}';\n?>`;
        }

        if (file.endsWith('.js')) {
            return `// JS Script for ${prompt}\nconsole.log("${prompt} - ${file} loaded.");`;
        }

        if (file.endsWith('.css')) {
            return `/* ${prompt} Styles */\nbody{font-family:sans-serif;background:#0f1724;color:#fff;}`;
        }

        return syntax.example || `// ${file} placeholder`;
    }

    // Show copy buttons
    function showFiles(files){
        copyContainer.innerHTML='';
        Object.keys(files).forEach(f=>{
            const btn = document.createElement("button");
            btn.textContent = `Copy ${f}`;
            btn.addEventListener('click',()=>{navigator.clipboard.writeText(files[f]); alert(f+' copied!');});
            copyContainer.appendChild(btn);
        });
    }

    // Generate project
    generateBtn.addEventListener('click', ()=>{
        const prompt = promptEl.value.trim() || "MyProject";
        const plan = analyzePrompt(prompt);

        const files = {};
        plan.files.forEach(f=>{
            files[f] = generateCode(f, prompt, plan.lang);
        });

        codeEl.textContent = files[plan.files[0]];
        showFiles(files);
    });

    // Optional HTML preview (for index.html)
    previewBtn.addEventListener('click', ()=>{
        const prompt = promptEl.value.trim() || "MyProject";
        const plan = analyzePrompt(prompt);
        const files = {};
        plan.files.forEach(f=>{
            files[f] = generateCode(f, prompt, plan.lang);
        });
        if(files['index.html']){
            const blob = new Blob([files['index.html']],{type:'text/html'});
            const iframe = document.getElementById("preview");
            iframe.src = URL.createObjectURL(blob);
        }
    });

    // Download project as ZIP
    downloadBtn.addEventListener('click', ()=>{
        const prompt = promptEl.value.trim() || "MyProject";
        const plan = analyzePrompt(prompt);
        const files = {};
        plan.files.forEach(f=>{
            files[f] = generateCode(f, prompt, plan.lang);
        });

        const zip = new JSZip();
        Object.keys(files).forEach(f=>zip.file(f, files[f]));
        zip.generateAsync({type:'blob'}).then(content=>{
            const a = document.createElement('a');
            a.href = URL.createObjectURL(content);
            a.download = 'ProjectBuilder.zip';
            a.click();
        });
    });

})();